# Generated by Django 4.0.1 on 2022-01-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Davlat', 'verbose_name_plural': 'Davlatlar'},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name_ru',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name_ru',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name_ru',
            new_name='name_en',
        ),
    ]
