# Generated by Django 4.0.1 on 2022-01-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Yangi'), (1, 'Qabul qilingan'), (2, 'Qaytarilgan'), (3, "Yo'lda"), (4, 'Yetkazib berilgan'), (5, 'Yopilgan')], default=0),
        ),
    ]
